"""
Unit-cell translation for RABDAM crystal-neighbour construction.

Translates the symmetry-expanded unit-cell atom coordinates by -1, 0, and +1 unit cells along 
the crystallographic a, b, and c axes to form a 3x3x3 parallelepiped of neighbouring cells.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
import math

from crystal.symmetry import (
    SymmetryExpandedAtom,
    SymmetryExpandedStructure,
    UnitCellParameters,
)


class CrystalTranslationError(ValueError):
    """Raised when RABDAM cannot translate a symmetry-expanded unit cell."""


@dataclass(frozen=True)
class CartesianVector:
    """A Cartesian vector in Angstroms."""

    x: float
    y: float
    z: float


@dataclass(frozen=True)
class UnitCellTranslationVectors:
    """
    Cartesian translation vectors for one full step along a, b, and c.

    These vectors are derived from the unit-cell lengths and angles. A translated
    atom at integer cell offset (i, j, k) is placed at:

        xyz' = xyz + i*a_vector + j*b_vector + k*c_vector
    """

    a: CartesianVector
    b: CartesianVector
    c: CartesianVector


@dataclass(frozen=True)
class TranslatedAtom:
    """
    One atom in the translated 3x3x3 crystal block.

    translated_atom_index:
        One-based serial number in the translated block atom list.

    unit_cell_atom_index:
        One-based index of the symmetry-expanded unit-cell atom that was copied.

    source_atom_index:
        Zero-based reader index of the original asymmetric-unit atom.

    symmetry_operation_index:
        One-based index of the space-group operation that generated the source
        unit-cell atom.

    is_identity_symmetry_operation:
        True when the source unit-cell atom was generated by the identity
        symmetry operation.

    translation_a, translation_b, translation_c:
        Integer unit-cell offsets applied along the crystallographic a, b, and c
        axes.

    x, y, z:
        Cartesian coordinates in Angstroms after applying the whole-cell
        translation.
    """

    translated_atom_index: int
    unit_cell_atom_index: int
    source_atom_index: int
    symmetry_operation_index: int
    is_identity_symmetry_operation: bool
    translation_a: int
    translation_b: int
    translation_c: int
    x: float
    y: float
    z: float


@dataclass(frozen=True)
class TranslatedCrystalBlock:
    """
    Symmetry-expanded unit-cell atoms translated into neighbouring cells.

    With translation_range=1, this contains the central unit cell plus all cells
    offset by -1, 0, or +1 along each of a, b, and c: 27 copies total.
    """

    atoms: tuple[TranslatedAtom, ...]
    unit_cell: UnitCellParameters
    translation_vectors: UnitCellTranslationVectors
    translation_range: int
    source_unit_cell_atom_count: int


def translate_expanded_unit_cell(
    expanded_structure: SymmetryExpandedStructure,
    *,
    translation_range: int = 1,
) -> TranslatedCrystalBlock:
    """
    Translate a symmetry-expanded unit cell into a neighbouring crystal block.
    """

    return translate_atoms(
        atoms=expanded_structure.atoms,
        unit_cell=expanded_structure.unit_cell,
        translation_range=translation_range,
    )


def translate_atoms(
    *,
    atoms: Iterable[SymmetryExpandedAtom],
    unit_cell: UnitCellParameters,
    translation_range: int = 1,
) -> TranslatedCrystalBlock:
    """
    Translate symmetry-expanded atoms by integer unit-cell offsets.
    """

    atom_tuple = tuple(atoms)
    if not atom_tuple:
        raise CrystalTranslationError(
            "Cannot translate an empty symmetry-expanded atom list."
        )

    if translation_range < 0:
        raise CrystalTranslationError(
            f"translation_range must be non-negative, got {translation_range!r}."
        )

    vectors = unit_cell_translation_vectors(unit_cell)
    translated_atoms: list[TranslatedAtom] = []

    for a_offset in range(-translation_range, translation_range + 1):
        for b_offset in range(-translation_range, translation_range + 1):
            for c_offset in range(-translation_range, translation_range + 1):
                shift = translation_vector_for_offsets(
                    vectors,
                    a_offset=a_offset,
                    b_offset=b_offset,
                    c_offset=c_offset,
                )

                for atom in atom_tuple:
                    translated_atoms.append(
                        TranslatedAtom(
                            translated_atom_index=len(translated_atoms) + 1,
                            unit_cell_atom_index=atom.unit_cell_atom_index,
                            source_atom_index=atom.source_atom_index,
                            symmetry_operation_index=atom.symmetry_operation_index,
                            is_identity_symmetry_operation=(
                                atom.is_identity_symmetry_operation
                            ),
                            translation_a=a_offset,
                            translation_b=b_offset,
                            translation_c=c_offset,
                            x=float(atom.x + shift.x),
                            y=float(atom.y + shift.y),
                            z=float(atom.z + shift.z),
                        )
                    )

    expected_count = len(atom_tuple) * (2 * translation_range + 1) ** 3
    if len(translated_atoms) != expected_count:
        raise CrystalTranslationError(
            "Failed to generate the expected translated crystal block: "
            f"expected {expected_count} atoms, got {len(translated_atoms)}."
        )

    return TranslatedCrystalBlock(
        atoms=tuple(translated_atoms),
        unit_cell=unit_cell,
        translation_vectors=vectors,
        translation_range=translation_range,
        source_unit_cell_atom_count=len(atom_tuple),
    )


def unit_cell_translation_vectors(
    unit_cell: UnitCellParameters,
) -> UnitCellTranslationVectors:
    """
    Convert unit-cell parameters into Cartesian a, b, and c vectors:

        a_vector = (a, 0, 0)
        b_vector = (b cos(gamma), b sin(gamma), 0)
        c_vector = (
            c cos(beta),
            c (cos(alpha) - cos(beta) cos(gamma)) / sin(gamma),
            c v / sin(gamma),
        )

    where v is the volume of a unit parallelepiped with the same angles as the
    unit cell.
    """

    validate_unit_cell_for_translation(unit_cell)

    alpha = math.radians(unit_cell.alpha)
    beta = math.radians(unit_cell.beta)
    gamma = math.radians(unit_cell.gamma)

    cos_alpha = math.cos(alpha)
    cos_beta = math.cos(beta)
    cos_gamma = math.cos(gamma)
    sin_gamma = math.sin(gamma)

    volume_factor_squared = (
        1
        - cos_alpha**2
        - cos_beta**2
        - cos_gamma**2
        + 2 * cos_alpha * cos_beta * cos_gamma
    )

    if volume_factor_squared <= 0:
        raise CrystalTranslationError(
            f"Invalid unit-cell geometry for translation: {unit_cell!r}."
        )

    volume_factor = math.sqrt(volume_factor_squared)

    return UnitCellTranslationVectors(
        a=CartesianVector(unit_cell.a, 0.0, 0.0),
        b=CartesianVector(
            unit_cell.b * cos_gamma,
            unit_cell.b * sin_gamma,
            0.0,
        ),
        c=CartesianVector(
            unit_cell.c * cos_beta,
            unit_cell.c * ((cos_alpha - cos_beta * cos_gamma) / sin_gamma),
            unit_cell.c * (volume_factor / sin_gamma),
        ),
    )


def validate_unit_cell_for_translation(unit_cell: UnitCellParameters) -> None:
    """Validate that unit-cell parameters can produce Cartesian vectors."""

    if unit_cell.a <= 0 or unit_cell.b <= 0 or unit_cell.c <= 0:
        raise CrystalTranslationError(
            f"Invalid unit-cell lengths: {unit_cell!r}."
        )

    if not all(0 < angle < 180 for angle in (unit_cell.alpha, unit_cell.beta, unit_cell.gamma)):
        raise CrystalTranslationError(
            f"Invalid unit-cell angles: {unit_cell!r}."
        )

    if math.isclose(math.sin(math.radians(unit_cell.gamma)), 0.0, abs_tol=1e-12):
        raise CrystalTranslationError(
            f"Invalid unit-cell gamma angle for translation: {unit_cell!r}."
        )


def translation_vector_for_offsets(
    vectors: UnitCellTranslationVectors,
    *,
    a_offset: int,
    b_offset: int,
    c_offset: int,
) -> CartesianVector:
    """
    Return the Cartesian shift for integer offsets along a, b, and c.
    """

    return CartesianVector(
        x=(
            a_offset * vectors.a.x
            + b_offset * vectors.b.x
            + c_offset * vectors.c.x
        ),
        y=(
            a_offset * vectors.a.y
            + b_offset * vectors.b.y
            + c_offset * vectors.c.y
        ),
        z=(
            a_offset * vectors.a.z
            + b_offset * vectors.b.z
            + c_offset * vectors.c.z
        ),
    )


def translated_coordinates_as_tuples(
    translated_block: TranslatedCrystalBlock,
) -> tuple[tuple[float, float, float], ...]:
    """Return only xyz coordinates from a translated crystal block."""

    return tuple((atom.x, atom.y, atom.z) for atom in translated_block.atoms)
